// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics_query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAnalytics = `-- name: CreateAnalytics :exec
INSERT INTO analytics (id, urlId, uniqueClicks, totalClicks)
VALUES (
    gen_random_uuid(),
    $1,
    0,
    0
)
RETURNING id, urlid, uniqueclicks, totalclicks
`

func (q *Queries) CreateAnalytics(ctx context.Context, urlid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createAnalytics, urlid)
	return err
}

const getAllAnalytics = `-- name: GetAllAnalytics :many
SELECT id, urlid, uniqueclicks, totalclicks FROM analytics
`

func (q *Queries) GetAllAnalytics(ctx context.Context) ([]Analytic, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytic
	for rows.Next() {
		var i Analytic
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Uniqueclicks,
			&i.Totalclicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsByUrlId = `-- name: GetAnalyticsByUrlId :one
SELECT id, urlid, uniqueclicks, totalclicks FROM analytics WHERE urlId = $1
`

func (q *Queries) GetAnalyticsByUrlId(ctx context.Context, urlid uuid.UUID) (Analytic, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsByUrlId, urlid)
	var i Analytic
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Uniqueclicks,
		&i.Totalclicks,
	)
	return i, err
}

const incrementClicksById = `-- name: IncrementClicksById :exec
UPDATE analytics
   SET totalClicks = totalClicks + 1
WHERE id = $1
`

func (q *Queries) IncrementClicksById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementClicksById, id)
	return err
}

const incrementClicksByUrlId = `-- name: IncrementClicksByUrlId :exec
UPDATE analytics
   SET totalClicks = totalClicks + 1
WHERE urlId = $1
RETURNING id, urlid, uniqueclicks, totalclicks
`

func (q *Queries) IncrementClicksByUrlId(ctx context.Context, urlid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementClicksByUrlId, urlid)
	return err
}

const incrementTotalClicks_UniqueClicksByUrlId = `-- name: IncrementTotalClicks_UniqueClicksByUrlId :exec
UPDATE analytics
   SET totalClicks = totalClicks + 1,
   uniqueClicks = uniqueClicks + 1
WHERE urlId = $1
`

func (q *Queries) IncrementTotalClicks_UniqueClicksByUrlId(ctx context.Context, urlid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementTotalClicks_UniqueClicksByUrlId, urlid)
	return err
}

const incrementUniqueClicksById = `-- name: IncrementUniqueClicksById :exec
UPDATE analytics
   SET uniqueClicks = uniqueClicks + 1
WHERE id = $1
`

func (q *Queries) IncrementUniqueClicksById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementUniqueClicksById, id)
	return err
}

const incrementUniqueClicksByUrlId = `-- name: IncrementUniqueClicksByUrlId :exec
UPDATE analytics
   SET uniqueClicks = uniqueClicks + 1
WHERE urlId = $1
`

func (q *Queries) IncrementUniqueClicksByUrlId(ctx context.Context, urlid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementUniqueClicksByUrlId, urlid)
	return err
}
