// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clicksbydates_query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClicksByDate = `-- name: CreateClicksByDate :exec
INSERT INTO clicksbydate (id, urlId, date, clicks)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    1
)
RETURNING id, urlid, date, clicks
`

type CreateClicksByDateParams struct {
	Urlid uuid.UUID
	Date  string
}

func (q *Queries) CreateClicksByDate(ctx context.Context, arg CreateClicksByDateParams) error {
	_, err := q.db.ExecContext(ctx, createClicksByDate, arg.Urlid, arg.Date)
	return err
}

const getClicksByDatesById = `-- name: GetClicksByDatesById :many
SELECT id, urlid, date, clicks FROM clicksbydate
WHERE id = $1
`

func (q *Queries) GetClicksByDatesById(ctx context.Context, id uuid.UUID) ([]Clicksbydate, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByDatesById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clicksbydate
	for rows.Next() {
		var i Clicksbydate
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Date,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByDatesByIdDate = `-- name: GetClicksByDatesByIdDate :many
SELECT id, urlid, date, clicks FROM clicksbydate
WHERE id = $1 AND date = $2
`

type GetClicksByDatesByIdDateParams struct {
	ID   uuid.UUID
	Date string
}

func (q *Queries) GetClicksByDatesByIdDate(ctx context.Context, arg GetClicksByDatesByIdDateParams) ([]Clicksbydate, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByDatesByIdDate, arg.ID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clicksbydate
	for rows.Next() {
		var i Clicksbydate
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Date,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByDatesByUrlId = `-- name: GetClicksByDatesByUrlId :many
SELECT id, urlid, date, clicks FROM clicksbydate
WHERE urlId = $1
`

func (q *Queries) GetClicksByDatesByUrlId(ctx context.Context, urlid uuid.UUID) ([]Clicksbydate, error) {
	rows, err := q.db.QueryContext(ctx, getClicksByDatesByUrlId, urlid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clicksbydate
	for rows.Next() {
		var i Clicksbydate
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Date,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByDatesByUrlIdDate = `-- name: GetClicksByDatesByUrlIdDate :one
SELECT id, urlid, date, clicks FROM clicksbydate
WHERE urlId = $1 AND date = $2
`

type GetClicksByDatesByUrlIdDateParams struct {
	Urlid uuid.UUID
	Date  string
}

func (q *Queries) GetClicksByDatesByUrlIdDate(ctx context.Context, arg GetClicksByDatesByUrlIdDateParams) (Clicksbydate, error) {
	row := q.db.QueryRowContext(ctx, getClicksByDatesByUrlIdDate, arg.Urlid, arg.Date)
	var i Clicksbydate
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Date,
		&i.Clicks,
	)
	return i, err
}

const incrementClicksByDateByUrlIdDate = `-- name: IncrementClicksByDateByUrlIdDate :exec
UPDATE clicksbydate
   SET clicks = clicks + 1
WHERE urlId = $1 AND date = $2
`

type IncrementClicksByDateByUrlIdDateParams struct {
	Urlid uuid.UUID
	Date  string
}

func (q *Queries) IncrementClicksByDateByUrlIdDate(ctx context.Context, arg IncrementClicksByDateByUrlIdDateParams) error {
	_, err := q.db.ExecContext(ctx, incrementClicksByDateByUrlIdDate, arg.Urlid, arg.Date)
	return err
}
