// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: countries_query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCountryClicks = `-- name: CreateCountryClicks :exec
INSERT INTO countries (id, urlId, country, clicks)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    1
)
RETURNING id, urlid, country, clicks
`

type CreateCountryClicksParams struct {
	Urlid   uuid.UUID
	Country string
}

func (q *Queries) CreateCountryClicks(ctx context.Context, arg CreateCountryClicksParams) error {
	_, err := q.db.ExecContext(ctx, createCountryClicks, arg.Urlid, arg.Country)
	return err
}

const getCountriesById = `-- name: GetCountriesById :one
SELECT id, urlid, country, clicks FROM countries
WHERE id = $1
`

func (q *Queries) GetCountriesById(ctx context.Context, id uuid.UUID) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountriesById, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Country,
		&i.Clicks,
	)
	return i, err
}

const getCountriesByUrlId = `-- name: GetCountriesByUrlId :many
SELECT id, urlid, country, clicks FROM countries
WHERE urlId = $1
`

func (q *Queries) GetCountriesByUrlId(ctx context.Context, urlid uuid.UUID) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountriesByUrlId, urlid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Country,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryClicksByUrlIdDate = `-- name: GetCountryClicksByUrlIdDate :one
SELECT id, urlid, country, clicks FROM countries
WHERE urlId = $1 AND country = $2
`

type GetCountryClicksByUrlIdDateParams struct {
	Urlid   uuid.UUID
	Country string
}

func (q *Queries) GetCountryClicksByUrlIdDate(ctx context.Context, arg GetCountryClicksByUrlIdDateParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, getCountryClicksByUrlIdDate, arg.Urlid, arg.Country)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Country,
		&i.Clicks,
	)
	return i, err
}

const incrementCountryClicks = `-- name: IncrementCountryClicks :exec
UPDATE countries
SET clicks = clicks + 1
WHERE urlId = $1 AND country = $2
`

type IncrementCountryClicksParams struct {
	Urlid   uuid.UUID
	Country string
}

func (q *Queries) IncrementCountryClicks(ctx context.Context, arg IncrementCountryClicksParams) error {
	_, err := q.db.ExecContext(ctx, incrementCountryClicks, arg.Urlid, arg.Country)
	return err
}
