// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Analytic struct {
	ID           uuid.UUID
	Urlid        uuid.UUID
	Uniqueclicks int32
	Totalclicks  int32
}

type Clicksbydate struct {
	ID     uuid.UUID
	Urlid  uuid.UUID
	Date   string
	Clicks int32
}

type Country struct {
	ID      uuid.UUID
	Urlid   uuid.UUID
	Country string
	Clicks  int32
}

type Referrer struct {
	ID     uuid.UUID
	Urlid  uuid.UUID
	Source string
	Clicks int32
}

type Shortenurl struct {
	ID          uuid.UUID
	Originalurl string
	Shorturl    string
	Customalias string
	Createdat   sql.NullTime
	Clicks      int32
	Isactive    bool
	Description string
}
