// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: referrers_query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createReferrer = `-- name: CreateReferrer :exec
INSERT INTO referrers (id, urlId, source, clicks)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    1
)
RETURNING id, urlid, source, clicks
`

type CreateReferrerParams struct {
	Urlid  uuid.UUID
	Source string
}

func (q *Queries) CreateReferrer(ctx context.Context, arg CreateReferrerParams) error {
	_, err := q.db.ExecContext(ctx, createReferrer, arg.Urlid, arg.Source)
	return err
}

const getReferrerById = `-- name: GetReferrerById :one
SELECT id, urlid, source, clicks FROM referrers
WHERE id = $1
`

func (q *Queries) GetReferrerById(ctx context.Context, id uuid.UUID) (Referrer, error) {
	row := q.db.QueryRowContext(ctx, getReferrerById, id)
	var i Referrer
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Source,
		&i.Clicks,
	)
	return i, err
}

const getReferrerBySourceUrlId = `-- name: GetReferrerBySourceUrlId :one
SELECT id, urlid, source, clicks FROM referrers
WHERE urlId = $1 AND source = $2
`

type GetReferrerBySourceUrlIdParams struct {
	Urlid  uuid.UUID
	Source string
}

func (q *Queries) GetReferrerBySourceUrlId(ctx context.Context, arg GetReferrerBySourceUrlIdParams) (Referrer, error) {
	row := q.db.QueryRowContext(ctx, getReferrerBySourceUrlId, arg.Urlid, arg.Source)
	var i Referrer
	err := row.Scan(
		&i.ID,
		&i.Urlid,
		&i.Source,
		&i.Clicks,
	)
	return i, err
}

const getReferrersByUrlId = `-- name: GetReferrersByUrlId :many
SELECT id, urlid, source, clicks FROM referrers
WHERE urlId = $1
`

func (q *Queries) GetReferrersByUrlId(ctx context.Context, urlid uuid.UUID) ([]Referrer, error) {
	rows, err := q.db.QueryContext(ctx, getReferrersByUrlId, urlid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Referrer
	for rows.Next() {
		var i Referrer
		if err := rows.Scan(
			&i.ID,
			&i.Urlid,
			&i.Source,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementReferrerClicks = `-- name: IncrementReferrerClicks :exec
UPDATE referrers
SET clicks = clicks + 1
WHERE urlId = $1 AND source = $2
`

type IncrementReferrerClicksParams struct {
	Urlid  uuid.UUID
	Source string
}

func (q *Queries) IncrementReferrerClicks(ctx context.Context, arg IncrementReferrerClicksParams) error {
	_, err := q.db.ExecContext(ctx, incrementReferrerClicks, arg.Urlid, arg.Source)
	return err
}
