// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shorten_url_query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createShortenURL = `-- name: CreateShortenURL :one
INSERT INTO shortenUrl (
    id, originalUrl, shortUrl, customAlias, createdAt, clicks, isActive, description
)
VALUES (
    gen_random_uuid(),
    $1, $2, $3,
    NOW(),
    $4, $5, $6
)
RETURNING id, originalurl, shorturl, customalias, createdat, clicks, isactive, description
`

type CreateShortenURLParams struct {
	Originalurl string
	Shorturl    string
	Customalias string
	Clicks      int32
	Isactive    bool
	Description string
}

func (q *Queries) CreateShortenURL(ctx context.Context, arg CreateShortenURLParams) (Shortenurl, error) {
	row := q.db.QueryRowContext(ctx, createShortenURL,
		arg.Originalurl,
		arg.Shorturl,
		arg.Customalias,
		arg.Clicks,
		arg.Isactive,
		arg.Description,
	)
	var i Shortenurl
	err := row.Scan(
		&i.ID,
		&i.Originalurl,
		&i.Shorturl,
		&i.Customalias,
		&i.Createdat,
		&i.Clicks,
		&i.Isactive,
		&i.Description,
	)
	return i, err
}

const deleteShortenURLById = `-- name: DeleteShortenURLById :exec
DELETE FROM shortenUrl WHERE Id = $1
`

func (q *Queries) DeleteShortenURLById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShortenURLById, id)
	return err
}

const deleteShortenURLByShortUrl = `-- name: DeleteShortenURLByShortUrl :exec
DELETE FROM shortenUrl WHERE shortUrl = $1
`

func (q *Queries) DeleteShortenURLByShortUrl(ctx context.Context, shorturl string) error {
	_, err := q.db.ExecContext(ctx, deleteShortenURLByShortUrl, shorturl)
	return err
}

const getAllShortens = `-- name: GetAllShortens :many
SELECT id, originalurl, shorturl, customalias, createdat, clicks, isactive, description FROM shortenUrl
`

func (q *Queries) GetAllShortens(ctx context.Context) ([]Shortenurl, error) {
	rows, err := q.db.QueryContext(ctx, getAllShortens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shortenurl
	for rows.Next() {
		var i Shortenurl
		if err := rows.Scan(
			&i.ID,
			&i.Originalurl,
			&i.Shorturl,
			&i.Customalias,
			&i.Createdat,
			&i.Clicks,
			&i.Isactive,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortenURLByShortUrl = `-- name: GetShortenURLByShortUrl :one
SELECT id, originalurl, shorturl, customalias, createdat, clicks, isactive, description FROM shortenUrl WHERE shortUrl = $1
`

func (q *Queries) GetShortenURLByShortUrl(ctx context.Context, shorturl string) (Shortenurl, error) {
	row := q.db.QueryRowContext(ctx, getShortenURLByShortUrl, shorturl)
	var i Shortenurl
	err := row.Scan(
		&i.ID,
		&i.Originalurl,
		&i.Shorturl,
		&i.Customalias,
		&i.Createdat,
		&i.Clicks,
		&i.Isactive,
		&i.Description,
	)
	return i, err
}

const incrementClick = `-- name: IncrementClick :exec
UPDATE shortenUrl
   SET clicks = clicks + 1
WHERE id = $1
`

func (q *Queries) IncrementClick(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementClick, id)
	return err
}

const updateShortenURLById = `-- name: UpdateShortenURLById :exec
UPDATE shortenUrl
   SET originalUrl = $2, customAlias = $3, description = $4
WHERE id = $1
`

type UpdateShortenURLByIdParams struct {
	ID          uuid.UUID
	Originalurl string
	Customalias string
	Description string
}

func (q *Queries) UpdateShortenURLById(ctx context.Context, arg UpdateShortenURLByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateShortenURLById,
		arg.ID,
		arg.Originalurl,
		arg.Customalias,
		arg.Description,
	)
	return err
}

const updateShortenURLStatusById = `-- name: UpdateShortenURLStatusById :exec
UPDATE shortenUrl
   SET isActive = $2
WHERE id = $1
`

type UpdateShortenURLStatusByIdParams struct {
	ID       uuid.UUID
	Isactive bool
}

func (q *Queries) UpdateShortenURLStatusById(ctx context.Context, arg UpdateShortenURLStatusByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateShortenURLStatusById, arg.ID, arg.Isactive)
	return err
}

const updateShortenURLStatusByShortUrl = `-- name: UpdateShortenURLStatusByShortUrl :exec
UPDATE shortenUrl
   SET isActive = $2
WHERE shortUrl = $1
`

type UpdateShortenURLStatusByShortUrlParams struct {
	Shorturl string
	Isactive bool
}

func (q *Queries) UpdateShortenURLStatusByShortUrl(ctx context.Context, arg UpdateShortenURLStatusByShortUrlParams) error {
	_, err := q.db.ExecContext(ctx, updateShortenURLStatusByShortUrl, arg.Shorturl, arg.Isactive)
	return err
}
